=== publisha/shakespeare_repo/resources/shakespeare_play.dtd
<!ELEMENT shakespeareplay (dramatis_personae?,play?)>
<!ELEMENT dramatis_personae (dramatis_head?,(charactergroup|charactername)+,play_location?)>
<!ELEMENT charactergroup (#PCDATA)>
<!ELEMENT charactername (#PCDATA | character_role)*>
<!ELEMENT character_role (#PCDATA)>
<!ELEMENT play ((act,(((firstscene|scene)+,location?,(stage_directions|stage_action|character|prose|verseline|song)+))*)*)>
<!ELEMENT location (#PCDATA | scene_image)*>
<!ELEMENT dramatis_head (#PCDATA)>
<!ELEMENT play_location (#PCDATA)>
<!ELEMENT act (#PCDATA)>
<!ELEMENT firstscene (#PCDATA)>
<!ELEMENT scene (#PCDATA)>
<!ELEMENT stage_directions (#PCDATA)>
<!ELEMENT stage_action (#PCDATA)>
<!ELEMENT character (#PCDATA | stage_directions_inline)*>
<!ELEMENT prose (#PCDATA | stage_directions_inline)*>
<!ELEMENT stage_directions_inline (#PCDATA)>
<!ELEMENT verseline (#PCDATA | stage_directions_inline)*>
<!ELEMENT song (#PCDATA)>
<!ELEMENT scene_image (#PCDATA)>
<!ATTLIST scene_image href CDATA #REQUIRED>
<!ATTLIST shakespeareplay title CDATA #REQUIRED>

=== publisha/shakespeare_repo/text_of_plays/merry_wives_of_windsor.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE shakespeareplay SYSTEM "shakespeare_play.dtd" []>
<shakespeareplay title="The Merry Wives of Windsor"> <dramatis_personae> <dramatis_head>Dramatis Personae</dramatis_head> <charactername>Sir John Falstaff</charactername> <charactername>Fenton, <character_role>a young gentleman</character_role></charactername> <charactername>Shallow, <character_role>a country justice</character_role></charactername> <charactername>Slender, <character_role>cousin to Shallow</character_role></charactername> <charactername>Gentlemen of Windsor</charactername> <charactername>Ford</charactername> <charactername>Page</charactername> <charactername>William Page, <character_role>a boy, son to Page</character_role></charactername> <charactername>Sir Hugh Evans, <character_role>a Welsh parson</character_role></charactername> <charactername>Doctor Caius, <character_role>a French physician</character_role></charactername> <charactername>Host of the Garter Inn</charactername> <charactername>Followers of Falstaff</charactername> <charactername>Bardolph</charactername> <charactername>Pistol</charactername> <charactername>Nym</charactername> <charactername>Robin, <character_role>page to Falstaff</character_role></charactername> <charactername>Simple, <character_role>servant to Slender</character_role></charactername> <charactername>Rugby, <character_role>servant to Doctor Caius</character_role></charactername> <charactername>Mistress Ford</charactername> <charactername>Mistress Page</charactername> <charactername>Mistress Anne Page, <character_role>her daughter</character_role></charactername> <charactername>Mistress Quickly, <character_role>servant to Doctor Caius</character_role></charactername> <charactername>Servants to Page, Ford, etc</charactername> <play_location>Windsor, and the neighbourhood</play_location> </dramatis_personae> <play> <act>Act I</act> <firstscene>Scene 1</firstscene> <location>Windsor. Before Page&#8217;s house</location> <stage_directions>Enter Justice Shallow, Slender, and Sir Hugh Evans</stage_directions> <character>Shallow</character> <prose>Sir Hugh, persuade me not; I will make a Star Chamber matter of it; if he were twenty Sir John Falstaffs, he shall not abuse Robert Shallow, esquire</prose> <character>Slender</character> <prose>In the county of Gloucester, Justice of Peace, and Coram</prose> <character>Shallow</character> <prose>Ay, cousin Slender, and Custalorum</prose> <character>Slender</character> <prose>Ay, and Ratolorum too; and a gentleman born, Master Parson, who writes himself &#8216;Armigero&#8217; in any bill, warrant, quittance, or obligation-&#8217;Armigero.&#8217;</prose> <character>Shallow</character> <prose>Ay, that I do; and have done any time these three hundred years</prose> <character>Slender</character> <prose>All his successors, gone before him, hath done&#8217;t; and all his ancestors, that come after him, may: they may give the dozen white luces in their coat</prose> <character>Shallow</character> <prose>It is an old coat</prose> <character>Evans</character> <prose>The dozen white louses do become an old coat well; it agrees well, passant; it is a familiar beast to man, and signifies love</prose> <character>Shallow</character> <prose>The luce is the fresh fish; the salt fish is an old coat</prose> <character>Slender</character> <prose>I may quarter, coz</prose> <character>Shallow</character> <prose>You may, by marrying</prose> <character>Evans</character> <prose>It is marring indeed, if he quarter it</prose> <character>Shallow</character> <prose>Not a whit</prose> <character>Evans</character> <prose>Yes, py&#8217;r lady! If he has a quarter of your coat, there is but three skirts for yourself, in my simple conjectures; but that is all one. If Sir John Falstaff have committed disparagements unto you, I am of the church, and will be glad to do my benevolence, to make atonements and</prose> <prose>compremises between you</prose> <character>Shallow</character> <prose>The Council shall hear it; it is a riot</prose> <character>Evans</character> <prose>It is not meet the Council hear a riot; there is no fear of Got in a riot; the Council, look you, shall desire to hear the fear of Got, and not to hear a riot; take your vizaments in that</prose> <character>Shallow</character> <prose>Ha! o&#8217; my life, if I were young again, the sword should end it</prose> <character>Evans</character> <prose>It is petter that friends is the sword and end it; and there is also another device in my prain, which peradventure prings goot discretions with it. There is Anne Page, which is daughter to Master George Page, which is pretty virginity</prose> <character>Slender</character> <prose>Mistress Anne Page? She has brown hair, and speaks small like a woman</prose> <character>Evans</character> <prose>It is that fery person for all the orld, as just as you will desire; and seven hundred pounds of moneys, and gold, and silver, is her grandsire upon his death&#8217;s-bed-Got deliver to a joyful resurrections!-give, when she is able to overtake seventeen years old. It were a goot motion if we leave our pribbles and prabbles, and desire a marriage between Master Abraham and Mistress Anne Page</prose> <character>Shallow</character> <prose>Did her grandsire leave her seven hundred pound?</prose> <character>Evans</character> <prose>Ay, and her father is make her a petter penny</prose> <character>Shallow</character> <prose>I know the young gentlewoman; she has good gifts</prose> <character>Evans</character> <prose>Seven hundred pounds, and possibilities, is goot gifts</prose> <character>Shallow</character> <prose>Well, let us see honest Master Page. Is Falstaff there?</prose> <character>Evans</character> <prose>Shall I tell you a lie? I do despise a liar as I do despise one that is false; or as I despise one that is not true. The knight Sir John is there; and, I beseech you, be ruled by your well-willers. I will peat the door for Master Page. [Knocks]What, hoa! Got pless your house here!</prose> <character>Page</character> <prose> [Within]Who&#8217;s there?</prose> <stage_directions>Enter Page</stage_directions> <character>Evans</character> <prose>Here is Got&#8217;s plessing, and your friend, and Justice   Shallow; and here young Master Slender, that peradventures shall tell you another tale, if matters grow to your likings</prose> <character>Page</character> <prose>I am glad to see your worships well. I thank you for my venison, Master Shallow</prose> <character>Shallow</character> <prose>Master Page, I am glad to see you; much good do it your good heart! I wish&#8217;d your venison better; it was ill kill&#8217;d. How doth good Mistress Page?-and I thank you always with my heart, la! with my heart</prose> <character>Page</character> <prose>Sir, I thank you</prose> <character>Shallow</character> <prose>Sir, I thank you; by yea and no, I do</prose> <character>Page</character> <prose>I am glad to see you, good Master Slender</prose> <character>Slender</character> <prose>How does your fallow greyhound, sir? I heard say he was outrun on Cotsall</prose> <character>Page</character> <prose>It could not be judg&#8217;d, sir</prose> <character>Slender</character> <prose>You&#8217;ll not confess, you&#8217;ll not confess</prose> <character>Shallow</character> <prose>That he will not. &#8216;Tis your fault; &#8216;tis your fault; &#8216;tis a good dog</prose> <character>Page</character> <prose>A cur, sir</prose> <character>Shallow</character> <prose>Sir, he&#8217;s a good dog, and a fair dog. Can there be more said? He is good, and fair. Is Sir John Falstaff here?</prose> <character>Page</character> <prose>Sir, he is within; and I would I could do a good office between you</prose> <character>Evans</character> <prose>It is spoke as a Christians ought to speak</prose> <character>Shallow</character> <prose>He hath wrong&#8217;d me, Master Page</prose> <character>Page</character> <prose>Sir, he doth in some sort confess it</prose> <character>Shallow</character> <prose>If it be confessed, it is not redressed; is not that so, Master Page? He hath wrong&#8217;d me; indeed he hath; at a word, he hath, believe me; Robert Shallow, esquire, saith he is wronged</prose> <character>Page</character> <prose>Here comes Sir John</prose> <stage_directions>Enter Sir John Falstaff, Bardolph, Nym, and Pistol</stage_directions> <character>Falstaff</character> <prose>Now, Master Shallow, you&#8217;ll complain of me to the King?</prose> <character>Shallow</character> <prose>Knight, you have beaten my men, kill&#8217;d my deer, and broke open my lodge</prose> <character>Falstaff</character> <prose>But not kiss&#8217;d your keeper&#8217;s daughter</prose> <character>Shallow</character> <prose>Tut, a pin! this shall be answer&#8217;d</prose> <character>Falstaff</character> <prose>I will answer it straight: I have done all this. That is now answer&#8217;d</prose> <character>Shallow</character> <prose>The Council shall know this</prose> <character>Falstaff</character> <prose>&#8216;Twere better for you if it were known in counsel: you&#8217;ll be laugh&#8217;d at</prose> <character>Evans</character> <prose>Pauca verba, Sir John; goot worts</prose> <character>Falstaff</character> <prose>Good worts! good cabbage! Slender, I broke your head; what matter have you against me?</prose> <character>Slender</character> <prose>Marry, sir, I have matter in my head against you; and against your cony-catching rascals, Bardolph, Nym, and Pistol. They carried me to the tavern, and made me drunk, and afterwards pick&#8217;d my pocket</prose> <character>Bardolph</character> <prose>You Banbury cheese!</prose> <character>Slender</character> <prose>Ay, it is no matter</prose> <character>Pistol</character> <prose>How now, Mephostophilus!</prose> <character>Slender</character> <prose>Ay, it is no matter</prose> <character>Nym</character> <prose>Slice, I say! pauca, pauca; slice! That&#8217;s my humour</prose> <character>Slender</cha
